### ISSUE TITLE
Optionen beim Erfassen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#103]
Wunsch

**Comment by barbalex** [comment]
was ist gemeint?

**Comment by csalzmann** [comment]
Gute Frage! Streichen! 

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch
