### ISSUE TITLE
Beobachtungen Export falsches Datum

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#105]
BeobMutWann im Export stimmt nicht mit tatsächlicher Mutation überein (im Export 1 Tag zu früh, in der FloraDB wirds richtig angezeigt)

**Comment by barbalex** [comment]
Genau genommen stimmt es überein: "2016-01-06T23:00:00.000Z" zum Beispiel ist gemäss ISO-Standard (https://en.wikipedia.org/wiki/ISO_8601) der korrekte Wert für den 7.1.2016, wenn man sich in unserer Zeitzone befindet. Denn "2016-01-07T00:00:00.000Z" wäre der entsprechende Wert in Greenwich.

Was passiert? 

- In der Benutzeroberfläche zeigt dir Javascript den Wert so an, wie du ihn erwartest.
- Im Export liefert SQL den Wert, ohne ihn benutzerfreundlich anzupassen

Ich schau mal, ob ich den Wert in SQL benutzerfreundlich umwandeln kann.

**Comment by barbalex** [comment]
hm. In MySQL (der Datenbank) sind korrekte Werte im korrekten Format enthalten. Der View liefert ebenfalls korrekte Werte. Dann übernimmt eine Fremdbibliothek die Daten vom View und lässt dich sie downloaden. Worauf sie als Text-Version des an sich korrekten ISO-Formats erscheinen, das aber so nicht benutzerfreundlich ist.

Ich bin ehrlich gesagt sprachlos.

Wenn ich die Anwendung neu aufbaue kann ich das genau so machen wie in arteigenschaften.ch. Dort ist zwar CouchDB statt MySQL dahinter, aber ich vermute, das mit den Daten klappt besser. Ausserdem können wir dann auch direkt in xlsx exportieren.

Ich schlage vor, wir vertagen dieses Problem. Es ist ja kaum prioritär.

**Comment by csalzmann** [comment]
Lieber Alex

Es ist in der Tat absolut nicht prioritär. Ich habs auch nur per Zufall gemerkt.

Lieber Gruss, Charlotte


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
