### ISSUE TITLE
Beobachtungen lassen sich nicht immer zuordnen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#108]
Habe schon zweimal aktualisiert, trotzdem lassen sich einige Beobachtungen nicht mehr aus den "nicht zuzuordnenden" lösen. Im Beispiel alle von Adolf Frick 1900 an abwärts.

![bildschirmfoto 2015-12-16 um 18 42 18](https://cloud.githubusercontent.com/assets/6047564/11848817/f0fd9512-a424-11e5-8b12-0ea8321c51ab.png)

**Comment by barbalex** [comment]
sollte in der neuen Version nicht passieren
