### ISSUE TITLE
Feldkontrollen - ausschneiden und einfügen funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#109]
Anfänglich wird es richtig angezeigt, nach "neu laden" jedoch ist Feldkontrolle wieder am alten Ort, an der eingefügten Stelle erscheint die Feldkontrolle dann komplett ohne Inhalt und wird mit "kein Jahr, kein Typ" angezeigt.

Kopieren/Einfügen funktioniert aber!

**Comment by barbalex** [comment]
ist umgesetzt
