### ISSUE TITLE
Qualitätskontrolle - Fehlerhafte Anzeige (Fehler werden nicht angezeigt)

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#110]
Hat meiner Meinung nach lange Zeit super funktioniert. 

Jetzt aber keine Anzeige mehr von div. Fehlern, z.B. EK im laufenden Jahr ohne TPop/Pop-Bericht, Massn-Bericht. 
Habe auch gemerkt, dass Anzeige von Fehler nicht konstant ist und wechselt. Z.B. wenn Status Pop/TPop nicht übereinstimmt. Je nachdem wird Fehler angezeigt oder nicht (wenn man mehrmals auf "erneut prüfen" drückt). Aber auch dann werden nicht alle Fehler angezeigt, fehlende Berichte z.B. wurden nie angezeigt. Liegt es am neuen (?) Feld "Suchen"?

**Comment by barbalex** [comment]
Ich habe versucht, es nachzuvollziehen, mit den ersten paar Aktionsplanarten bis und mit Campanula cervicaria.

Ich kann das aber nicht nachvollziehen.

Gibt es eine Art, bei der ich das nachvollziehen kann?

**Comment by csalzmann** [comment]
Z.B. Liparis, Pop 60

Habe jetzt TPop-Bericht 2015 entfernt, da sollte es jetzt eine Fehlermeldung geben.


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by csalzmann** [comment]
![bildschirmfoto 2016-01-06 um 17 44 34](https://cloud.githubusercontent.com/assets/6047564/12148198/73d584da-b49d-11e5-87b5-0665b5b19418.png)

**Comment by barbalex** [comment]
danke, ich kann es jetzt nachvollziehen

**Comment by csalzmann** [comment]
In der Qualitätskontrolle Problem z.B. auch mit nicht kompatiblen Stati Pop und TPop. Bsp. Ophrys araneola. Siehe Screenshot. Ich korrigiere die Fehler nun aber in meinen APs, der nächste Export hat diese Fehler dann nicht mehr drin. 

![bildschirmfoto 2016-01-08 um 17 05 08](https://cloud.githubusercontent.com/assets/6047564/12202518/99ba580e-b62a-11e5-9f8b-08d6d747e60b.png)

**Comment by csalzmann** [comment]
Fehler bei Gentiana cruciata. TPop 0001.2 mit Freiwilligen-Kontrolle 2015, aber ohne TPop-Bericht 2015. Ergibt keine Fehlermeldung. Ich korrigiere das jetzt aber.

**Comment by barbalex** [comment]
Die Kontrolle prüft folgendes:
- es gibt eine Ansiedlung oder Ansaat vor dem Berichtsjahr
- es gibt eine Kontrolle im Berichtsjahr
- es gibt keinen TPop-Bericht im Berichtsjahr

Die TPop 2 der Pop 1 von Gentiana cruciata hatte nie eine Massnahme. Daher erfolgte keine Fehlermeldung

**Comment by barbalex** [comment]
Bezüglich Ansaatversuchen wird momentan geprüft:
- Pop mit Status Ansaatversuch, es gibt TPop mit Status aktuell
- Pop mit Status Ansaatversuch, es gibt TPop mit Status ursprünglich erloschen

Was möchtest du prüfen?

**Comment by csalzmann** [comment]
Dies ist gut, damit auch ein Massnahmenbericht erstellt wird. Aber es sollte auch für ursprüngliche Pops mit EKs ein Bericht erstellt werden. Dann fehlte diese Kontrolle bis anhin? Ist die schwierig, noch zu erstellen?

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by csalzmann** [comment]
Upps, Überschneidung. Betr. Ansaatversuche: das ist gut, ich brauch die beide!

**Comment by barbalex** [comment]
o.k., jetzt verstehe ich:
- es gibt eine Kontrolle, die prüft, ob Ansiedlung/Ansaat existiert, ob im Berichtsjahr eine Kontrolle durchgeführt war und ob daher ein MASSNAHMEN-Bericht verfasst wurde
- es gibt eine Kontrolle, die prüfen SOLLTE, ob im Berichtsjahr eine Kontrolle durchgeführt wurde und ob daher ein TEILPOPULATIONS-Bericht verfasst wurde. Bloss: diese Kontrolle reagiert auch nur, wenn eine  Ansiedlung/Ansaat existiert. Und das sollte sie nicht.
Ich passe das an.

**Comment by barbalex** [comment]
Die Kontrolle, die prüft, ob im Berichtsjahr eine Kontrolle durchgeführt wurde und ob daher ein Teilpopulations-Bericht verfasst wurde, ist nun korrigiert. Es sollte nun immer eine Meldung erscheinen, wenn eine Kontrolle durchgeführt wurde, darüber aber nicht berichtet wurde.

Leider kann ich nur mit etwas Aufwand eine Liste über alle Arten erstellen. Bitte melde, wenn du das brauchst.

Bitte sag mir in einem anderen Issue genau, was du gemeldet haben willst, wenn die Population ein Ansaatversuch ist.
