### ISSUE TITLE
Export Beobachungen mit Status TPop/Pop ergänzen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#111]
Bitte Export Beobachtungen mit Status Pop/TPop ergänzen

**Comment by csalzmann** [comment]
Sowie auch Feld "Introduit" aus Beobachtung -> Ziel: Vergleich Status Pop/TPop APFlora und infoflora (verschiedene Vorkommen sind bei infoflora aus ursprünglich klassiert, dafür handelt es sich um Ansiedlungen)

**Comment by barbalex** [comment]
umgesetzt
