### ISSUE TITLE
Erfolgskontrolle (Zwischen-)Ziele löschen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#113]
Bitte bei allen Arten Kontrolltyp (Zwischen-)Ziele löschen. Diese generieren nämlich immer wieder Probleme bei der EK-Auswertung, wenn da nicht dran gedacht wird, dass die auch noch drin sind.

**Comment by barbalex** [comment]
Das habe ich vor einiger Zeit schon gemacht.

Wie ich sehe gibt es aber noch den Kontrolltyp "Zwischenziel" selbst.

Soll ich den auch entfernen?

**Comment by csalzmann** [comment]
Das ist aber komisch. Im Export Kontrollen sind diese Zahlen immer noch drin, siehe Screenshot Export von gestern.

Bitte bei Gelegenheit dann auch noch Zwischenziel und Ziel in der Eingabemaske löschen.




---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
ouch. Die Kontrolltypen sind ja nicht per id verknüpft sondern als Text enthalten - daher hat meine Abfrage keine mit Typ 5 (=Zwischenziel) gefunden.

Was soll aus den 11 Kontrollen mit Typ Zwischenziel und den 319 Kontrollen mit Typ Ziel entstehen? Alle löschen?

Diese Kontrollen sind angehängt - du musst allerdings auf github schauen, im Mail erscheinen sie nicht: es gibt dafür 
[tpopkontr_ziel.xlsx](https://github.com/FNSKtZH/apflora/files/82728/tpopkontr_ziel.xlsx)
[tpopkontr_zwischenziel.xlsx](https://github.com/FNSKtZH/apflora/files/82727/tpopkontr_zwischenziel.xlsx)

im Mail einen Link "view it on github"

**Comment by csalzmann** [comment]
Kurz und schmerzlos: alles löschen!

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
gemacht
