### ISSUE TITLE
kml Import funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#114]
Habe kml in Karte gezogen. Wird in den Ebenen zwar angezeigt, nicht jedoch auf der Karte. Ausserdem - sobald man "neu laden" macht ist es wieder weg. Das muss aber so sein bei temporärer Ebene, oder?

![bildschirmfoto 2016-01-08 um 10 59 13](https://cloud.githubusercontent.com/assets/6047564/12195369/0821efa2-b5f7-11e5-9583-3c6b9c863454.png)

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
