### ISSUE TITLE
Eierlegende Wollmilchsau - inkl. Art-Verantwortliche

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#115]
Könntest Du dies auch noch einfüllen? Wäre super, weil wir Tabelle nächste Woche an die Artverantwortlichen schicken wollen - dann können sie sich gleich selektieren

**Comment by barbalex** [comment]
erledigt

**Comment by barbalex** [comment]
hier noch die Datei

herzliche Grüsse
Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2016 um 16:43 schrieb csalzmann <notifications@github.com>:
