### ISSUE TITLE
AP-Ziele - nach Jahr ordnen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#116]
Aktuell nicht der Fall und daher sehr unübersichtlich, Bsp. Himantoglossum

![bildschirmfoto 2016-01-14 um 10 16 36](https://cloud.githubusercontent.com/assets/6047564/12320259/f1f362a0-baa7-11e5-8e7f-8b16467d5571.png)

**Comment by barbalex** [comment]
ist bei mir lokal behoben
benötigt aber einen Neustart des Servers
werde das einmal Nachts machen

**Comment by csalzmann** [comment]
Danke!

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch
