### ISSUE TITLE
Potenzieller Wuchs-/Ansiedlungsort nicht in Grundmenge

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#122]
Der Potenzielle Wuchsort wird zwar in der Grundmenge erwähnt - nicht jedoch gezählt. Ich nehme an der Grund liegt darin, dass man auf Ebene TPop ja angibt, dass potenz. Wuchs-/Ansiedlungsorte nicht AP-Bericht relevant sind ("Nein, kein Vorkommen"). Aktuelles Bsp.: Cardamine dentata, Pop 10.

![bildschirmfoto 2016-01-19 um 16 10 58](https://cloud.githubusercontent.com/assets/6047564/12422434/489552a8-bec7-11e5-83f4-ac987a4dd357.png)

**Comment by barbalex** [comment]
du hast wohl recht
ich bin heute mit dem Notebook (mac, daher kein Access...) unterwegs
werde morgen kontrollieren

**Comment by barbalex** [comment]
Die Kandidatin hat 100 Punkte: Du hast mit deiner Vermutung ins Schwarze getroffen. Ist korrigiert
