### ISSUE TITLE
Export Kontrollen für WebGISBUN

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#124]
Die Datenbank für den Import ins WebGISBUN von Lieni ist so aufgebaut, dass es für die 3 verschiedenen Zähleinheiten und zugehörigen Methoden jeweils eine Spalte gibt. Könntest Du dafür bitte nochmals einen Export machen, bei dem diese Spalten wie früher wieder enthalten sind?
Alternativ müsste man Lieni fragen, ob er seine Struktur an die aktuelle 1-Spalten-Methode anpasst. Was meinst Du ist sinnvoller?

**Comment by barbalex** [comment]
das ist gemäss mail vom 22.1.2016 geregelt: Export ohne Zählungen als punktshapefile durch dich an Lieni zu liefern
