### ISSUE TITLE
Export Populationen und MassnBerichte

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#125]
Könntest Du mir bitte bitte in diesen Export noch relevant für AP-Bericht einfügen? Danke!

**Comment by barbalex** [comment]
AP-Bericht-Relevanz ist im Feld "TPopApBerichtRelevant" auf der Teilpopulation definiert.

Es wäre gefährlich, dass im allgemeinen Export für Populationen zu ergänzen: Denn diese Information liegt tiefer unten im Strukturbaum. Sobald man tiefere Stufen verknüpft, kann man die Abfrage meist nur noch für bestimmte Fragestellungen designen.

Darum ist diese Information bisher auch nur im Export für Teilpopulationen enthalten.

Ich kann eine Abfrage/Export erstellen, welche die Populationen auflistet und jeweils anzeigt: 
- ob mindestens eine Teilpopulation existiert, die AP-relevant ist
- ob mindestens eine Teilpopulation existiert, die nicht AP-relevant ist
- oder (mit viel mehr Aufwand) zählen, wie viele jeder Kategorie existieren

Was willst du?
Mit welchen Feldern?
Als Export auf apflora.ch oder im AdminTool?

Massnahmenberichte gibt es auf Ebene Population und auf Ebene Teilpopulation.
Auf Ebene Teilpopulation wäre es einfach, eine Abfrage zu erstellen, welche die AP-Relevanz enthält.
Auf Ebene Population stellen sich dieselben Fragen wie bei der Population selbst.
Welche Ebene hast du gemeint?

**Comment by csalzmann** [comment]
Lieber Alex

OK, Du musst wohl wissen, wofür ich das Ganze will.

Für den Jahresbericht soll ich ja Übersichtskarten erstellen. Dort sollten doch eigentlich die gleiche Info wie in der Grundmenge dargstellt werden (so hab ich’s mir zumindest vorgestellt). Wenn ich TPops darstelle, dann habe ich aber viel zu viel Info auf so einer Karte - drum arbeite ich auf Pop-Ebene. Anbei ein Beispiel. 

Eigentlich wäre es aber schon schön, auch die historischen darzustellen. Müsste ich die wohl noch anders darstellen als die ursprünglich erloschenen? Wenn ich überlege: wohl ja! Dann bleiben noch die ausserkantonalen. Die wollte ich eigentlich v.a. weg haben. V.a., weil wir von info flora keine aktuellen Daten haben und die Beurteilung des Status wohl oft falsch sein könnte. Aber auch das ist natürlich diskussionswürdig.

Könnt ich die Ausserkantonalen denn irgendwie wegbringen?

Morgen ist Karin im Büro, werds dann sowieso mit ihr besprechen, ob das überhaupt nötig ist. Also deswegen im Moment keine grossen Arbeiten!


Lieber Gruss, Charlotte





---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
das tönt nach einem separaten View für diesen Zweck
man könnte die ausserkantonalen wie in der Qualitätskontrolle im View ermitteln
oder im GIS, in dem du sowieso den Plan erstellst, oder?

**Comment by csalzmann** [comment]
Stimmt, die ausserkantonalen würd ich mit einer GIS-Selektion wegkriegen! Danke! Hab diese Möglichkeit vor lauter Tabellen ganz vergessen..!

Betr. historische/aktuelle: wir haben uns drauf geeinigt, dass wir einfach klar sagen, was auf den Karten zu sehen ist und dass die historischen halt nicht von den anderen ursprünglichen erloschenen zu unterscheiden sind.


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
Du brauchst also einen View mit allen Information von Art, AP und Population und der Angabe, ob mindestens eine Teilpopulation existiert, die AP-relevant ist?

Und sinngleich für Populations-Massnahmen-Berichte?

**Comment by barbalex** [comment]
ist im Prinzip umgesetzt - sag, wenn du andere Felder brauchst
