### ISSUE TITLE
Zusätzliche Übersichtstabelle in Jahresbericht

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#128]
Könntest Du bitte noch eine neue Tabelle in den Jahresbericht einfügen? Es wäre eine zusammenfassende Tabelle, welche pro Art jeweils die Summe der aktuellen ursprünglichen und aktuellen angesiedelten Pops sowie das Total (also alle aktuellen) anzeigt.

**Comment by barbalex** [comment]
gemacht
