### ISSUE TITLE
Qualitätskontrolle Berichte

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#129]
Ausserkantonale nicht berücksichtigen

**Comment by barbalex** [comment]
Ich nehme an, das heisst generell: nur für AP-Bericht relevante berücksichtigen. Korrekt?

**Comment by csalzmann** [comment]
Jein.

Wir geben ja auch ausserkantonale Pops ein, und wenn ich dort eine EK mache, ist ja dann interessant für mich zu wissen, wieviele Pflanzen dort sind, kommt auch das rein. Wenn da was mit Koordinaten oder Nr und so nicht stimmt, find ich das schon noch praktisch. Aber Berichte machen wir sicher nicht bei Ausserkantonalen.

Lieber Gruss, Charlotte

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
o.k., gemacht

Damit die Änderungen aktiv werden, muss ich den Daten-Server neu starten. Falls ich von dir nicht innert 5 Minuten ein NEEEEIIIIIINNNNNN!!!!! höre, mache ich das, in der Annahme, dass ihr am Mittagessen seid
