### ISSUE TITLE
Qualitätskontrolle - Sonderfall wenn zwischendurch erloschen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#130]
Wie lösen wir diese Fehlermeldung? :

Chronologisch
1. Ansiedlung
2. EK Anz > 0
3. EK Anz = 0 -> TPop unsicher/erloschen
4. Ansaat -> TPop mit Status Ansaatversuch

Gibt Fehlermeldung mit Status Ansaatversuch, weil zuvor einmal Pflanzen in EK gezählt wurden. Bsp. Campanula, TPop 3.5

**Comment by barbalex** [comment]
wir berücksichtigen nur die LETZTE Kontrolle
gemacht
