### ISSUE TITLE
Qualitätskontrolle - Sonderfall wenn TPop zwischendurch erloschen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#132]
Hier nochmals eine Knacknuss

Chronologie:

1. Ansiedlung
2. EK=0 -> Status erloschen
3. neue Ansiedlung, aber noch keine neue EK -> Status angesiedelt, aktuell gibt Fehlermeldung

**Comment by barbalex** [comment]
gleiches Problem bei: `Teilpopulation: Status ist "erloschen", der letzte Teilpopulations-Bericht meldet aber "aktuell"`

Problem gelöst, indem in beiden Fällen die Meldung nur erscheint, wenn seit der letzten Meldung keine Ansiedlung erfolgte.

Ich muss den api-Server neu starten, bevor die Änderung aktiv wird
