### ISSUE TITLE
Beobachtungen: wenn zugeordnet und TPop gelöscht verschwunden

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#133]
Habe bei O. palustris eine TPop gelöscht (TPop 1.1), die schon eine zugeordnete Beobachtung hatte (Walter Schmid-Fisler, 1965). Ich hatte eigentlich erwartet, dass die Beobachtung dann "frei" wird und ich sie einer anderen TPop zuordnen kann. Die Beobachtung ist jetzt aber verschwunden. ?

**Comment by barbalex** [comment]
richtig: Das war bisher nicht vorgesehen

Man müsste beim Löschen von TPop eine Abfrage ausführen, welche alle zugeordneten Beobachtungen freisetzt.

Im optimalen Fall würde das auf Ebene Datenbank passieren, d.h. mit einem Trigger. Das ist aber in MySQL leider nicht möglich. Wird aber in PostgreSQL möglich sein. Ich könnte das für die neue Version vorsehen.

Es reicht (in der bisherigen Anwendung) nicht nur, die Beobachtung wieder freizugeben. Das würde nämlich erst nach einem Reload des Browserfensters sichtbar. Also müsste die Anwendung auch noch die Daten und die Benutzeroberfläche aktualisieren. Das ist bei der jetzt verwendeten Technologie sehr aufwändig. Wäre aber in der nächsten Version verhältnismässig einfach. Das würde ich also auch auf apflora V2 aufschieben.

Ich könnte diesen Einzelfall manuell korrigieren, wenn ich die TPopId wüsste.

Besser wäre wohl, eine Abfrage zu kreieren, welche alle zugeordneten Beobachtungen, deren TPop nicht existieren, freisetzt. Das kostet wohl ca. 45 Minuten Arbeit.

Ich kann diese Abfrage nach dem Löschbefehl ausführen lassen. Aber wie gesagt: Du müsstest immer noch die Anwendung neu laden. Plus 15 Minuten Aufwand.

Ich glaube die Antwort ist klar, aber ihr seid Auftraggeber: Soll ich das machen?

**Comment by barbalex** [comment]
umgesetzt
