### ISSUE TITLE
Eierlegende Wollmilchsau, falscher Export

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#134]
Wenn man den individuellen Export / Art macht, erhält man als Export "Programme" statt die Sau.

**Comment by barbalex** [comment]
hm. Bei mir kam der richtige Export. Kannst du das wiederholbar provozieren?

**Comment by csalzmann** [comment]
Unglaublich! Jetzt funktioniert es!! Aber bitte glaub mir, dass das nicht so war. Die Programm-Exporte sind auch immer noch in meinem Download-Ordner. Hmm.

Hauptsache es läuft jetzt!



---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
ich glaub dir schon

manchmal ist es unglaublich, was z.B. der Cache des Browsers alles anstellen kann: Du rufst eine url auf, der Browser holt aber nicht die aktuellen Daten von apflora.ch sondern liefert dir etwas, was er selbst zwischengespeichert hat

na ja, mindestens könnte das solche dinge erklären, wenn sie danach nicht mehr wiederholt werden können...
