### ISSUE TITLE
Qualitätkontrolle erweitern

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#135]
Lieber Alex

Es braucht nochmals etwas in der Qualitätskontrolle. Habe die unmöglichen Kombinationen von Status, Berichte und Bekannt seit in Excel aufgelistet. Alle diese Fälle habe ich nun aber bereits in der FloraDB korrigiert.

Gibt es eine Übersicht über alle Kategorien Qualitätskontrollen? 
[Qualitätskontrolle_Fehler_20160218.xlsx](https://github.com/FNSKtZH/apflora/files/136365/Qualitatskontrolle_Fehler_20160218.xlsx)

**Comment by barbalex** [comment]
Hier die Liste. Ich muss sie noch nachführen:
https://docs.google.com/presentation/d/1x1qo7f6-FaJBe7SxxQmyECtR-Jxbl1rup4Wd0A9rg_0/edit?usp=docslist_api

**Comment by barbalex** [comment]
Duplikat von https://github.com/FNSKtZH/apflora/issues/180
