### ISSUE TITLE
Qualitätskontrolle - Bestandesentwicklung (Pop-Berichte)

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#136]
Gibt es dafür auch Qualitätskontrollen?

Mir ist grad per Zufall folgender Fehler untergekommen für 2015: Pop zunehmend, aber keine TPop zunehmend

Das dürfte eigentlich nicht sein, gleich wie (theoretisch): Pop abnehmend, aber keine TPop abnehmend

Die anderen Fälle sind wohl eher diffizil, da ja meist gutachterlich beurteilt. Evtl. zu besprechen!

**Comment by barbalex** [comment]
nein
bisher gibt es nur: "Population: letzter Pop-Bericht widerspricht dem Status, z.B. Status aktuell aber Bericht erloschen"

**Comment by barbalex** [comment]
Duplikat von https://github.com/FNSKtZH/apflora/issues/182
