### ISSUE TITLE
Teilpopulationen Export: 2 Ergänzungen (für WebGIS BUN Import)

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#138]
Bitte noch "TPop-Verantwortliche Person2 einfügen (nach TPopKataster-Nr) und "TPop bekannt seit" (nach TPp fuer AP-Bericht relevant)

**Comment by barbalex** [comment]
So früh?

;-)

**Comment by barbalex** [comment]
Ich habe jetzt nachgeschaut:

- "TPop-Verantwortliche Person" wäre die AP-Verantwortliche, richtig?

  Falls ja: die ist als "AP verantwortlich" schon drin.
  Möchtet ihr trotzdem das zusätzliche Feld erhalten?

- "TPop bekannt seit" ist schon drin, nach "TPop Status"

**Comment by csalzmann** [comment]
Lieber Alex

Danke. Das ist gut so.

Herzliche Grüsse, Charlotte

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
o.k., ich schliesse das issue
