### ISSUE TITLE
Admin Tool, Update funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#139]
Die Update-Funktion des Admin-Tools funktioniert noch nicht. Wenn man es doch probiert, landet man im Leeren (siehe Screenshot). Bin aktuell auf Version 2015-10-20. 

![bildschirmfoto 2016-03-16 um 17 45 59](https://cloud.githubusercontent.com/assets/6047564/13820890/9bf5a146-eb9f-11e5-84d6-acc6142eff42.png)

**Comment by barbalex** [comment]
in der nächsten Version repariert
