### ISSUE TITLE
Beobachtungen, Jahr wird nicht angezeigt

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#141]
Obwohl es in der Beobachtung unter A_NOTE einen Eintrag zum Jahr gibt, wird dieses im Stammbaum bei vielen Beobachtungen nicht angezeigt. Das wäre nötig, um einfach "bekannt seit" einzufüllen, ansonsten muss man immer in Beobachtung hineingehen um nachzusehen.
![beobachtung_jahr](https://cloud.githubusercontent.com/assets/6047564/14042098/09c84c68-f277-11e5-9b7e-f990b8383be6.JPG)

![beobachtung_jahr2](https://cloud.githubusercontent.com/assets/6047564/14042114/3c462534-f277-11e5-8814-1b9637f7d824.JPG)

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
