### ISSUE TITLE
csv Dateien 

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#142]
Auf Excel Mac 2016 und Excel PC 2010 geben die mit LibreOffice geöffneten und als xlsx abgespeicherten Daten eine Fehlermeldung. Was wirklich falsch ist, weiss ich nicht. Gemäss Deiner Aussage könnte es aber schon Datenverschiebungen geben.
Vermutlich ist dies schon lange so (beim PC ists mir schon länger aufgefallen), da wir bisher aber Excel Mac 2008 hatten und das nie einen Fehler rausgespuckt hat, hats mich nicht gekümmert.

Hier die Meldungen:

![bildschirmfoto 2016-03-30 um 15 59 17](https://cloud.githubusercontent.com/assets/6047564/14144875/e060707a-f691-11e5-9434-e6acd791b7f5.png)

![bildschirmfoto 2016-03-30 um 15 59 28](https://cloud.githubusercontent.com/assets/6047564/14144894/ef1a18e6-f691-11e5-8683-d67a5f5269e0.png)

**Comment by barbalex** [comment]
das passiert bei mir auch
ist unschön
aber die Dateien sind vollständig und korrekt - mindestens, wenn ich sie überprüft habe
werde das bei Gelegenheit mal anschauen

danke für die Meldung

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
