### ISSUE TITLE
EK: Reihenfolge Zähleinheiten wird geändert

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#143]
Bei der Eingabe wird die Reihenfolge der Zähleinheiten automatisch vertauscht. Z.B. gebe ich Pflanzen als Zähleinheit 1 ein und Blüten als Zähleinheit 2. Die Datenbank tauscht dann automatisch die Zähleinheiten aus. So sind Blüten bei erneutem Anklicken Zähleinheit 1 und Pflanzen Zähleinheit 2.

**Comment by barbalex** [comment]
wieso kommt es auf die Reihenfolge an?

**Comment by csalzmann** [comment]
Damit es mit der Auswertung der Ziele (Anz. Pfl./Triebe etc) einfacher geht. Du wolltest uns sonst ja mal eine Einführung machen, wie wir das mit dem Excel und Verknüpfungen händeln könnten. Wenn das klappt, ist die Reihenfolge tatsächlich nicht so wichtig. Frage ist aber trotzdem: warum wird die eingegebene Reihenfolge verändert, ist das kompliziert zu ändern?


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
Die Reihenfolge in von Datensätzen in einer Tabelle entspricht meist der Eingabereihenfolge.

Sich auf diese Reihenfolge zu verlassen ist aber vermutlich gefährlich, falls die Reihenfolge kritisch sein sollte. Darum habe ich gefragt. Wenn man z.B. die Tabelle aus einer Sicherung wiederherstellt, bin ich nicht so sicher, ob die Reihenfolge bleibt, v.a. wenn die Daten aus einer anderen Quelle stammen, z.B. beim Import von MySQL in PostgreSQL (der ja nun vorbei ist).

Im konkreten Fall sollte das von dir gewünschte Verhalten möglich sein, wenn die Daten beim Abholen aus der Datenbank bewusst NICHT sortiert werden.

**Comment by csalzmann** [comment]
Ich meine ja nicht den Export, sondern wenn man auf „neu laden“ geht, dann ist schon in der Datenbank die 1. und 2. Zähleinheit vertauscht.

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
Ja, will sie dann neu aus der Datenbank geholt wird und dabei sortiert wird. Werde es nach der Diskussion morgen anpassen

**Comment by barbalex** [comment]
...weil statt will - Handy...

**Comment by csalzmann** [comment]
Lieber Alex
Könntest Du nicht doch das mal versuchen? Die ändernde Reihenfolge stört uns bei der Eingabe. Danke!

**Comment by barbalex** [comment]
endlich umgesetzt: 7c2e6511b43bf1514c5c8ff9621b549c806a168c

**Comment by csalzmann** [comment]
funktioniert immer noch nicht!

**Comment by barbalex** [comment]
o.k., man lernt nie aus...

klappt jetzt wirklich
