### ISSUE TITLE
Beobachtungen, Zuordnung "hinkt"

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#147]
Reagiert manchmal nicht recht auf Zuordnungen. Z.Bsp. kam es jetzt schon mehrmals vor, dass ich eine Beobachtung zuordnen wollte, der Button "nicht beurteilt" blieb ausgefüllt, die TPop, der ich die Beobachtung tatsächlich zuordnen möchte war auch angewählt und keine Zuordnung fand satt.

Auch wenn ich eine Beobachtung einer anderen TPop zuordnen möchte, klappt das nicht immer. Im Bsp. die neue TP
![beobachtungen_popwechsel](https://cloud.githubusercontent.com/assets/6047564/20028784/36d1c138-a33b-11e6-98d6-8487b5d83616.JPG)
![beobachtungen_zugeordnent_nichtbeurteilt](https://cloud.githubusercontent.com/assets/6047564/20028785/39ce6d82-a33b-11e6-80ab-994f393228b6.JPG)

op angewählt, aber die Beobachtung immer noch bei der alten.

**Comment by csalzmann** [comment]
Erst "neu laden" und dann nochmals zuordnen hilft.

**Comment by csalzmann** [comment]
Es gibt jetzt auch ab und zu Fehlermeldungen, "Beobachtung konnte nicht zugeordnet werden". Ausgerechnet diese Beobachtungen sind dann aber am Ende zugeteilt (im Gegensatz zu obigen Fällen).
![beobachtung_konnte-nicht_zugeordnet_werden](https://cloud.githubusercontent.com/assets/6047564/20029245/6dfd60c0-a347-11e6-8ed3-94a675ef2fd7.JPG)

**Comment by csalzmann** [comment]
Habe 4 TPops von "nicht zuordnen" auf "nicht beurteilt" gestellt. Wurden auch neu unter "nicht beurteilte Beobachtungen" angezeigt. Ich konnte mit rechts Klick jedoch keine neue Population daraus gründen, Menü beinhaltete nur 3 Punkte (es müssen wohl diejenigen von den "nicht beurteilten" gewesen sein). Nach "neu laden" waren die 4 Beobachtungen wieder unter den "nicht zuzuordnende Beobachtungen" aufgelistet.

**Comment by csalzmann** [comment]
Immerhin wird dies er  Fehler in der DB sogar mit Fehlermeldung kommentiert

![beobachtung_nicht umgeteilt](https://cloud.githubusercontent.com/assets/6047564/20029796/78922854-a356-11e6-84be-223bc3f72b8d.JPG)

**Comment by csalzmann** [comment]
Neuer Versuch: zuerst bei den "nicht zuzuordnenden die Bemerkung löschen (es darf ja nur bei den zuzuordnenden Bemerkungen geben). Klicke ich nach dem löschen auf "nicht beurteilt", kommt "letzte Änderung wurde nicht gespeichert"
![beobachtung_letzteanderung nicht gespeichert](https://cloud.githubusercontent.com/assets/6047564/20029826/3123fe1a-a357-11e6-8eec-dbc74540ec6a.JPG)

**Comment by csalzmann** [comment]
"Letzte Änderung wurde nicht gespeichert" kommt auch, wenn auch dem Löschen oder Ändern der Texteingabe bei Bemerkungen auf eine andere "nicht zuzuordnende Beobachtung" klicke.

**Comment by barbalex** [comment]
Dieses Verhalten wird in der neuen Anwendung ganz anders gesteuert. Daher wird es dort auch ganz andere Fehler geben ;-).

Bitte nachhaken, wenn das Verhalten diesen Herbst noch funktionieren muss.

**Comment by barbalex** [comment]
Lieber Alex

Leider muss etwas von dem Zeugs noch diesen Herbst wieder funktionieren. Und zwar, dass ich zugeordnete oder nicht zuzuordnende Beobachtungen wieder auf nicht beurteilte stellen kann. Bei Liparis muss ich die Daten so bereitstellen, dass Jasmin den Aktionsplan aktualisieren kann - dafür muss ich auch einige Beobachtungen herumschieben.

Es wäre super, wenn dies bis zum nächsten Wochenende wieder läuft. Meinst Du, das geht? 


Herzliche Grüsse, Charlotte

**Comment by barbalex** [comment]
o.k., ich lege die neue Anwendung auf die Seite :-(
und wende mich morgen diesem Problem zu

lg, Alex

**Comment by barbalex** [comment]
Du hast hier ein paar unterschiedliche Sachen beschrieben. Ich bin daher nicht sicher, ob das alles nun bereinigt ist. Aber:

Kürzlich habe ich sichergestellt, dass die Anwendung nur erwartete Werte an die Datenbank schicken kann. Eine der neuen Anforderungen war, dass die Tabellen-ID ein Zahl war. Das ist auch bei fast allen Tabellen so. Ausser: bei den Beobachtungen von EvAB - dort ist diese ID eine GUID.

Darum scheiterten Aktualisierungen und Löschungen in der Tabelle apflora.beobzuordnung.

Ich habe das nun repariert.

Im selben ging es, deinen kürzlichen Wunsch zu erfüllen: du siehst jetzt immer, wie viele Beobachtungen es gibt.

**Comment by csalzmann** [comment]
Wow, Du bist wieder superschnell!

Super sieht man jetzt die Total-Anzahl Beobachtungen! 

Etwas hinkt noch, die findest sicher eine Lösung: Nicht zuzuordnende Beobachtungen kann man jetzt nicht mehr öffnen, es gibt sofort eine Fehlermeldung "Keine Daten für die Beobachtung erhalten".
![bildschirmfoto 2016-11-09 um 13 53 49](https://cloud.githubusercontent.com/assets/6047564/20139071/914bf8ee-a684-11e6-82ea-b81cb3c6f4cc.png)

**Comment by barbalex** [comment]
ist repariert
