### ISSUE TITLE
Total Anzahl zuzordnende Beobachtungen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#148]
Wäre es möglich, wenn nach "neueste 100" in Klammern jeweils stehen würde, vielviele Beobachtungen es ingesamt noch zuzuordnen gibt?  Problem: Ich muss Beobachtungen zuordnen, muss mir die Zeit dafür einplanen, weiss aber nicht, wieviele es denn überhaupt noch hat.

Habe nun Beobachtungen Export gemacht. Es gab bei beiden vorhandenen Exporten eine Fehlermeldung, es wurden aber trotzdem Daten in ein csv-File geschrieben. 

![export_beob_infospecies und evab](https://cloud.githubusercontent.com/assets/6047564/20028887/8faab254-a33d-11e6-9bd1-e71cd12bf2e5.JPG)

Habe dieses in Excel importiert und nach Art und Beobachtungen ohne Pop-Nr. gefiltert. Es spukte mir bei Liparis an 79 rsp 81 Datensätze raus, in der APFlora steht aber bei Beobachtungen (neueste 100).

**Comment by barbalex** [comment]
> Wäre es möglich, wenn nach "neueste 100" in Klammern jeweils stehen würde, vielviele Beobachtungen es ingesamt noch zuzuordnen gibt? Problem: Ich muss Beobachtungen zuordnen, muss mir die Zeit dafür einplanen, weiss aber nicht, wieviele es denn überhaupt noch hat.

In der neuen Version: Ja.
In der alten: nein.

Ich werde dafür ein neues issue erfasssen.

Bitte künftig pro Wunsch/Fehler ein separates issue erstellen.

**Comment by barbalex** [comment]
> Habe nun Beobachtungen Export gemacht. Es gab bei beiden vorhandenen Exporten eine Fehlermeldung, es wurden aber trotzdem Daten in ein csv-File geschrieben.

Das scheint ein neues Verhalten von Google Chrome zu sein: Das Tool, das für den Dowload verwendet wird, setzt einen speziellen Header um zu verhindern, dass Chrome die Datei in Chrome öffnet bzw. anzeigt. Chrome passt nun neustens dieser Header nicht und es meldet daher einen Fehler.

Den kann man ignorieren. Werde in apflora v3 (der neuen Version) versuchen, dass so was nicht passiert.

**Comment by barbalex** [comment]
> Habe dieses in Excel importiert und nach Art und Beobachtungen ohne Pop-Nr. gefiltert. Es spukte mir bei Liparis an 79 rsp 81 Datensätze raus, in der APFlora steht aber bei Beobachtungen (neueste 100).

Bei mir zeigt es korrekt 81 Datensätze an.
Kann es sein, dass du vorher über 19 Beobachtungen zugeordnet hast? Beim Zuordnen wird die Zahl nicht aktualisiert, erst wenn du die Art das nächste mal ladest.
