### ISSUE TITLE
Siegfried Karte - Sachinformation wird unerwünscht angezeigt

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#150]
Wenn man bei Siegfreidkarte auf Distanz messen geht, wird mit gelber Farbe Sachinformation (Blattnummer der Siegfriedkarte) flächendeckend angezeigt und Distanzmessung unmöglich. Wenn schon angezeigt (ich glaube nicht, das wir das brauchen), dann müsste man es unter Sachinformation anwählen können.

**Comment by csalzmann** [comment]
![siegfried_distanz](https://cloud.githubusercontent.com/assets/6047564/20029938/aee7542a-a35a-11e6-92cc-3a998dca9138.JPG)

**Comment by barbalex** [comment]
Uhm ja, das wird von Swisstopo so eingestellt.

Wird ev. schon möglich sein, dieses Verhalten zu verhindern. Aber ich möchte lieber keine komplizierten Änderungen an der alten Version mehr vornehmen, wenn sie nicht prioritär sind.

Denn diese Änderungen braucht eine tiefe Einarbeit in OpenLayers und GeoAdmin API.

Das muss ich dann sowieso machen, wenn ich den Kartenteil der neuen Anwendung aufbaue. Das mache ich dann aber mit einer anderen Technologie...

Bitte nachhaken, wenn das wichtig ist und diesen Herbst noch passieren muss.

**Comment by barbalex** [comment]
sollte in der neuen Version nicht mehr passieren
