### ISSUE TITLE
AdminTool

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#152]
Wenn ich auf "Adressen verwalten" gehe, gibts Laufzeitfehler 3151
![bildschirmfoto 2016-11-08 um 10 59 56](https://cloud.githubusercontent.com/assets/6047564/20094784/12bd0388-a5a3-11e6-8134-d4bdf25d9fbb.png)

**Comment by barbalex** [comment]
Der Server wurde seit dem letzten mal neu aufgesetzt.
Und da ist nun erst noch PostgreSQL 9.6 drauf.
Ich hab 9.6 gewählt, weil:
- es länger unterstützt wird als 9.5
- es potentiell VIEL schneller ist (was ich auch im lokalen Betrieb spüre)

Etwas überraschend scheint der Zugriff auf 9.6 mit demselben Treiber zu funktionieren wie bei 9.5. Mindestens muss ich bei mir gar nichts ändern und das admin-Tool funktioniert einwandfrei.

Der neue Server wurde ansonsten genau gleich konfiguriert, wie der letzte (Ports, Benutzer, Passwort).
Was geändert hat ist nur die IP des Servers. Wenn du aber für den Zugriff die URL verwendest (api.apflora.ch), müsste derselbe Treiber weiter funktionieren. Ev. hast du letztes mal die IP-Adresse eingesetzt?

Hier meine Konfiguration:
![odbc_driver_setup](https://cloud.githubusercontent.com/assets/669783/20095442/c84e8300-a5a5-11e6-95bc-54fbe0a56161.png)

**Comment by barbalex** [comment]
auf der Download-Site von PostgreSQL wird immer noch der Treiber von Ende Juli als aktuellster Treiber angeboten: https://www.postgresql.org/ftp/odbc/versions/msi/

Du musst den Treiber also nicht ersetzen.

**Comment by barbalex** [comment]
übrigens: Um meine Konfiguration zu sehen, musst du im mail den Link zur Webseite klicken ("view it on GitHub"): https://github.com/FNSKtZH/apflora/issues/152

**Comment by csalzmann** [comment]
Habe neue Version vom AdminTool runtergeladen und jetzt funktionierts, musste sonst nichts machen.  Danke!

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr
