### ISSUE TITLE
Eingabe Datum ohne Kalender unmöglich

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#153]
Wenn man Datum von Hand (also nicht über Kalender) eingibt mit Format DD.MM.JJJJ gibt sich bei der Eingabe des Jahres ein Fehler. Vermutlich wird Eingabe zu schnell gespeichert, man kommt gar nicht dazu, das 4-stellige Jahr einzugeben und schon kriegt man Fehlermeldung.
![bildschirmfoto 2016-11-09 um 13 41 28](https://cloud.githubusercontent.com/assets/6047564/20138754/6444553c-a682-11e6-9e46-ae4a1ee96638.png)

**Comment by barbalex** [comment]
Danke für die Meldung.
Wieder mal die neuen Kontrollen :-|

repariert
