### ISSUE TITLE
Pop/TPop-Name aktzeptiert keine "/"

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#154]
Gibt es irgendeinen Weg, dieses Zeichen trotzdem zu verwenden? Verwenden wir eben schon noch oft.
![bildschirmfoto 2016-11-10 um 08 53 46](https://cloud.githubusercontent.com/assets/6047564/20168985/39edd80a-a725-11e6-94cd-0882d344541d.png)

**Comment by barbalex** [comment]
Du hast einen ganz komplizierten Vorgang aufgedeckt, der mit Sicherheitsvorgaben in Webservern zu tun hat. Ich weiss nicht, ob ich das lösen kann.

Wenn nach dem / nicht viel Text kommt, klappt es bei mir. Wenn zwei oder mehr Wörter folgen, gibt es diesen Fehler:

    XMLHttpRequest cannot load https://api.apflora.ch/update/apflora/tabelle=pop/tabelleIdFeld=PopId/tabel…2146169906/feld=PopName/wert=mal%20schauen%20%2F%20ob%20es%20klappt/user=z. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://apflora.ch' is therefore not allowed access.

**Comment by csalzmann** [comment]
Bis anhin haben wir den Schrägstrich wie gesagt relativ häufig verwendet. Ich wollte nur eine Anpassung im Namen machen, da kam die Meldung. Es gibt also einige Namen, die wenn nicht geändert, akzeptiert werden. Wenn es ein generelles Problem wäre, dann dürften all diese Namen doch sowieso auch eine Fehlermeldung auslösen, oder?

Ehrlich gesagt kommt mir auch nicht grad einen Ersatz für den Schrägstrich in den Sinn..

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
Der Schrägstrich funktioniert in der Entwicklungs-Umgebung, nicht aber auf dem Live-Server.

Momentan habe ich keine Ahnung, was dies verursachen könnte.

Könntet ihr statt dem Schrägstrich "/" den vertikalen Strich verwenden: "|"?
Falls ja, könnte ich beim Speichern die Schrägstriche jeweils damit ersetzen.

Nebenbei: Der umgekehrte Schrägstrich "\" löst auch einen Fehler aus.

**Comment by csalzmann** [comment]
Lieber Alex

Ehrlich gesagt, schon etwas ungern, das ist ein doch recht geläufiges Zeichen. Aber bis auf weiteres machen wir das so natürlich, wir wollen ja weiterarbeiten können! Dann speicherst Du das bei Dir, dass Du alle „|“ umwandeln musst? (eigentlich unglaublich, dass ausgerechnet dieser blöde Strich (musste nachschauen, wie man das überhaupt mit Mac macht) funktioniert und ein normaler Schrägstrich nicht..!).

Herzliche Grüsse, Charlotte


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
Die Anwendung verwandelt jetzt beim Speichern / und \ in |. Und zwar für den Benutzer sichtbar.

Wir lassen diesen Issue offen - hoffentlich lässt sich das einmal lösen.

**Comment by csalzmann** [comment]
Danke! 
---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
