### ISSUE TITLE
Letzte Änderung nicht gespeichert - es können keine neuen TPops gegründet werden

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#155]
Vielleicht liegts gar nicht am Schrägstrich. Ich wollte jetzt ganz normal eine neue TPop eingeben, und hatte mind 3 Mal jetzt schon eine Fehlermeldung "letzte Änderung nicht gespeichert". 

Wie Du dem Screenshot entnehmen kannst, steht da ja kaum was drin was stören könnte.
![bildschirmfoto 2016-11-10 um 11 15 23](https://cloud.githubusercontent.com/assets/6047564/20172901/38644430-a737-11e6-9cc0-22acb19cbd13.png)

Nach "neu laden" ergab sich, dass überhaupt nichts von den Eingaben gespeichert wurde (ausser das eine neue leere TPop angefügt wurde).

![bildschirmfoto 2016-11-10 um 11 18 07](https://cloud.githubusercontent.com/assets/6047564/20172937/655f6c6c-a737-11e6-8afa-2a4fe1baece6.png)

OK. Ich kann keine neue TPop bilden. Fehlermeldung schon nach Nummereingabe und dann Klick in neues Feld

**Comment by barbalex** [comment]
Oh je. Nebenwirkungen von https? Bin grad beim Zahnarzt und mach das an Nachmittag

**Comment by barbalex** [comment]
Hm. Alles andere funktioniert wieder. Das hier funktioniert in der Entwicklungsumgebung. Aber nicht auf dem live server :-(

**Comment by csalzmann** [comment]
Danke für Deinen Einsatz!! Wir waren wirklich recht froh, heute hat Ilona wieder Daten eingegeben und wir auch das eine oder andere nachgeschaut.


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr
