### ISSUE TITLE
Beobachtungen auf CH Karten: Zoom to selected

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#157]
Wie wenn man auf CH-Karten zeigen klickt. Oder zumindest markieren, damit man schnell dorthin in der Karte kommt.

**Comment by csalzmann** [comment]
Manchmal wird die TPop auch markiert wie oben gewünscht, aber eben nicht immer. Habe auch noch nicht verstanden wann und wann nicht:).

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
