### ISSUE TITLE
Eingabe "bekannt seit"

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#159]
Dieses Feld ist ja zwingend für die Eingabe. Es stört aber den Arbeitsablauf, weil wir uns einfach nicht abgewöhnen können, zuerst den Status anwählen zu wollen. Vielleicht hats ja auch damit zu tun, dass wir Rechtshänderinnen sind. Auf jeden Fall, auch ich, tappe immer wieder in diese Falle.

Könntest Du "bekannt seit" nicht einfach in die Qualitätskontrolle aufnehmen und die zwingende Eingabe löschen?

**Comment by barbalex** [comment]
> Könntest Du "bekannt seit" nicht einfach in die Qualitätskontrolle aufnehmen und die zwingende Eingabe löschen?

Klar, aber das wäre recht aufwändig.

Ich hab mal was anderes versucht: "bekannt seit" kommt jetzt VOR den Stati. Im Prinzip müsste damit die Feldreihenfolge stimmen und das Problem behoben sein. Was meinst du?

**Comment by csalzmann** [comment]
Finde ich Super-Lösung!

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
...und jetzt noch optisch verbessert
