### ISSUE TITLE
Abfrage Eierlegende Wollmilchsau pro Art

### ISSUE THREAD

**Issue by kmarti** [FNSKtZH/apflora#160]
Lieber Alex

In der Tabelle, die nach dieser Abfrage (z.B. Anagallis minima) generiert wird, stimmen die Spalten nicht mit der Überschrift überein. Es ist ein ziemliches Durcheinander. Könntest Du das bitte mal anschauen.

Vielen Dank und herzliche Grüsse

Karin

**Comment by barbalex** [comment]
Hoi Karin

Bei mir funktioniert es, siehe Datei im Anhang (github unterstützt keine csv-Anhänge, darum die Antwort per email).

Irgend eine Vorgeschichte muss das bei dir bewirkt haben?
Versuch mal, die Anwendung neu zu öffnen.

Herzliche Grüsse
Alex
