### ISSUE TITLE
Qualitätskontrolle, Anzeigetempo

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#161]
Es wird schneller geschrieben als ausgewertet wird. So beginnen die meisten Qualitätskontrollen mit "juhuii", und nachher kommt trotzdem noch eine Liste mit Fehlern. Wenn die Fehlerliste kommt, kann es sein, dass sie nach ein paar Sekunden noch erweitert wird. Und: man weiss halt nicht, wie lange man warten muss und man kann sich in falscher Richtigkeit wiegen.

Es wäre angenehmer, lieber ein bisschen länger zu warten, dafür weiss man, dass das Resultat am Ende stimmt. Könntest Du das so einrichten oder ist das schwierig?

**Comment by barbalex** [comment]
hm, ja, das ist nicht optimal

Ich werde versuchen, in der neuen Version einen Fortschrittsbalken einzublenden. Ist aber nicht ganz unaufwändig. Können wir es diesen Winter noch so lassen, wie es ist?

**Comment by csalzmann** [comment]
Und wenn Du "einfach" mit der Ausgabe des Resultates wartest, bis alles fertig gerechnet ist? Ist das gleich schwierig wie Fortschrittsbalken? Ich befürchte eben, dass man bei der Schlusskontrolle etwas verpassen könnte, wenn man x Arten durchklickt und es auf den ersten Blick OK ausschaut.. Wenn gar noch kein Resultat steht, dann ist klar, dass man warten muss.

**Comment by barbalex** [comment]
gemacht

**Comment by csalzmann** [comment]
Du bist ein Held!

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
:-)
