### ISSUE TITLE
Qualitätskontrolle

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#162]
Könntest Du noch einbauen:

Pop darf nicht Ansaatversuch sein, wenn alle TPops erloschen

War aktuelles Beispiel, drum haben wirs gemerkt.

Evtl. gibt es mit dem Ansaatversuch als Pop noch weitere Tests einzubauen, habe dies noch nicht gecheckt

P.S. Qualitätskontrolle läuft viel schneller als vorher!

**Comment by barbalex** [comment]
gemacht: schau bei diesen Arten:

- "Himantoglossum hircinum (L.) Spreng. (Riemenzunge)"
- "Ophrys araneola Rchb. (Spinnen-Ragwurz)"
