### ISSUE TITLE
Qualitätskontrolle: Fehler EK Zähleinheiten

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#163]
Mal etwas Neues: es wird ein Fehler angezeigt, wo keiner ist: es werden Zähleinheiten vermisst, obwohl es die hat (Feldkontrolle) und im anderen Fall gar keine EKF existiert. Kannst Du mal schauen (siehe Screenshot)?
![bildschirmfoto 2016-12-20 um 11 45 18](https://cloud.githubusercontent.com/assets/6047564/21347737/332bf804-c6aa-11e6-98c1-0a7e268314d6.png)

**Comment by barbalex** [comment]
Zur ersten: das hier sind die Zählungen:

![2016-12-21_18h34_14](https://cloud.githubusercontent.com/assets/669783/21399481/2a707692-c7ac-11e6-898a-aac931c05734.png)

Wie du siehst, sind es vier (vermutlich musst du das auf github anschauen). Und eine davon hatte tatsächlich keine Zähleinheit. Ich habe sie gelöscht.

**Comment by barbalex** [comment]
Zur zweiten: Die verschwand nach der Korrektur der ersten. Worauf ich gemerkt habe, dass in beiden Fällen alle Kontrollen abgefragt wurde, statt Freiwilligen- bzw. Feld. Ist korrigiert.
