### ISSUE TITLE
Jahresbericht 2016 funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#164]
Es ist nicht möglich, einen Jahresbericht 2016 zu generieren
![bildschirmfoto 2016-12-21 um 14 07 07](https://cloud.githubusercontent.com/assets/6047564/21390356/cf2e0026-c786-11e6-89e8-3977ec6f23e8.png)

**Comment by barbalex** [comment]
Uups. Kümmere mich nach dem Training darum.

LG
Alex

Auf dem Handy geschrieben

**Comment by barbalex** [comment]
o.k., habe die Abfrage repariert und laufen gelassen
