### ISSUE TITLE
Jahresbericht 2016

### ISSUE THREAD

**Issue by kmarti** [FNSKtZH/apflora#166]
Lieber Alex

Ich hoffe, Du bist gut ins neue Jahr gestartet.

Im Jahresbericht 2016 sind in den Grundmengen von Aldrovanda vesiculosa 11 bekannte Populationen angegeben, 5 aktuelle und 5 erloschene. Es gibt aber 6 erloschene Populationen, die für den Jahresbericht relevant sind. Ich kann mir diesen Fehler nicht erklären.

Herzliche Grüsse

Karin

**Comment by barbalex** [comment]
Das Problem dürfte die Population 3 sein:

- sie hat PopHerkunft 202 ("angesiedelt nach Beginn AP, erloschen/nicht etabliert")
- sie ist aber bekannt seit 2004, während der AP erst 2006 gestartet ist

Ich habe das korrigiert (einfach den Status neu gesetzt, die Anwendung korrigiert das dann). Siehe den neuen Bericht im Anhang (nur auf github.com, nicht im Mail enthalten: du musst im Mail unten auf "view it on GitHub" klicken).

Übrigens ist die Population 1 mit "testName" komisch benannt
[2017 01 09 berJb 2016 aldrovanda korrigiert.pdf](https://github.com/FNSKtZH/apflora/files/693059/2017.01.09.berJb.2016.aldrovanda.korrigiert.pdf)
.
