### ISSUE TITLE
Jahresbericht, Feldlänge

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#167]
Für die Analyse stehen im Bericht nur 66 Zeichen zur Verfügung. Könntest Du bitte die Anzahl Zeichen analog der übrigen Felder erhöhen?

**Comment by barbalex** [comment]
66? Nein, es sind 255.
Das heisst: Die aktuelle Anwendung akzeptiert nur 255.
Die Datenbank schluckt tatsächlich aber unendlich viele Zeichen.
(apflora v3 akzeptiert daher momentan auch unendlich viele Zeichen)

Wieso kommst du auf 66? Kann ich das nachvollziehen?

**Comment by csalzmann** [comment]
Im Bericht werden beim Analyse-Feld 66 Zeichen angezeigt, die mit der Texteingabe gegen 0 abnehmen (siehe Attachment). Ich kann in diesem Feld viel weniger Text einfüllen als in den anderen Feldern. Das Analyse-Feld müsste so wie die anderen Felder sein.





---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
Hoi Charlotte

Das Attachment kann ich nicht finden. Bei mir sieht es so aus (nur auf GitHub sichtbar):

![2017-01-11_12h07_36](https://cloud.githubusercontent.com/assets/669783/21846272/b839cef6-d7f6-11e6-9a6a-d525de65e2a3.png)

**Comment by barbalex** [comment]
Ziel: Möglichst viele Felder

**Comment by barbalex** [comment]
o.k., jetzt kann man unbegrenzt Daten in die Analyse rein schreiben
