### ISSUE TITLE
Beobachtungen: Potamogeton aus EVAB fehlt komplett

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#169]
Unsere Herbar/Literaturrecherchen werden im EVAB als Prio 2 geführt - dann sollte dies doch auch als Beobachtung in der FloraDB sein. ?

**Comment by barbalex** [comment]
leider kann ich EVAB nicht öffnen, weil es bei mir abstürzt :-(
ich wollte nachschauen, was im Stand letztem Import vorhanden war

seit wann sind diese Daten in EVAB?

**Comment by barbalex** [comment]
Lag an der synonymen Art, daher selbes Problem wie hier: https://github.com/FNSKtZH/apflora/issues/117
Schliesse diesen issue, der andere bleibt offen
