### ISSUE TITLE
EK ausschneiden/einfügen: Datensatz geht verloren

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#184]
Dies ist eine wichtige Funktion, bitte entfernen (kopieren/einfügen funktioniert) oder flicken. Es ist blöd, wenn man Daten verliert - und bis im Juli arbeiten die Artverantwortlichen ja noch mit V1.

**Comment by barbalex** [comment]
Ich kann das leider nicht nachvollziehen.

Und mir auch nicht so einfach erklären. Denn beim Verschieben wird im Prinzip nur eine ID im Datensatz geändert. Entweder diese Operation gelingt und der Datensatz wurde verschoben. Oder sie misslingt und der Datensatz bleibt am alten Ort.

Die einzige Erklärung wäre, wenn diese ID falsch übermittelt würde. Allerdings würde der Server jede ID ablehnen, welche nicht existiert. Es könnte also höchstens sein, dass z.B. wenn man eine Feldkontrolle verschiebe, die Feldkontrolle einer anderen Teilpopulation angehängt würde und man weiss nicht, welche. Aber diesen Fall halte ich für sehr unwahrscheinlich.

Viel wahrscheinlicher ist, dass dein Browser irgend welche Cache-Probleme hatte, die du durch Neu-Laden von apflora.ch beheben können solltest.

Oder dass er wegen komischer Darstellungs-Problemen deinen Klick einer anderen Teilpopulation zugeordnet hat, als du meinst bzw. als du sahst.

**Comment by csalzmann** [comment]
Lieber Alex

Doch, das ist so. Und was gemein ist: man sieht den Fehler erst nach „neu laden“.

Siehe die beiden Screenshots, vor und nach „neu laden“:








Die kopierte EK 2015 ist nun leer (kein Jahr): (kein Typ).

Lieber Gruss, Charlotte


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
o.k., jetzt hab ich es auch begriffen :-)
und die Funktion ausgeschaltet
