### ISSUE TITLE
Liste der Qualitätskontrollen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#185]
Steht im Wiki nicht mehr zur Verfügung (Links zu Google Slides gelöscht). Wäre vielleicht gut, ich würde da auch mal einen Blick reinwerfen.

**Comment by barbalex** [comment]
https://github.com/barbalex/apf2/blob/master/src/modules/fetchQk.js#L20-L157, siehe https://github.com/barbalex/apf2/issues/75

Bitte benutzte von jetzt an https://github.com/barbalex/apf2/issues
