### ISSUE TITLE
WEBGISBUN Exporte

### ISSUE THREAD

**Issue by wunderli** [FNSKtZH/apflora#186]
Die Spalte mit Tpopchangeby enthält statt Namen das alte Datumsformat....
![bildschirmfoto 2018-04-25 um 08 47 30](https://user-images.githubusercontent.com/26789445/39230147-b0583b1a-4865-11e8-9e1c-ba1ff3d7932b.png)

**Comment by wunderli** [comment]
Lieber Alex

Habe nun für die WebGisBun-Abgabe alle neuen Exporte verwendet.
Da ich noch die erloschenen Tpop rausfiltern muss für die Abgabe, wäre ich sehr froh, wenn diese Spalte ebenfalls in den Exporten MassnahmenWebGisBun und KontrolleWebGisBun wären!
Ebenfalls sind bei diesen beiden Exporten MASSNCHANGEBY und KONTRCHANGEBY leer.

Zusammenfannend fehlen diese Spalten für die Abgabe:
Tpop-Export: TPOPKILMA und SAPTARTJAHR

Kontroll-Export: Tpop Staus, KONTRCHANGEBY, Tpop KontrID

Massnahmen-Export (aus ArcGis-Tauglich fürs digitalisieren notwendig):
AP Status, Umsetzung, Tpop Gemeinde, Tpop Flurname, Tpop Status, Massn GUID Alt, MASSNCHANGEBY

Wäre super, wenn du diese noch diese Woche anpassen könntest, damit ich das bald abgeben kann!

Liebe Grüsse

Anna

**Comment by barbalex** [comment]
> Die Spalte mit Tpopchangeby enthält statt Namen das alte Datumsformat....
Ist korrigiert. Danke für die Meldung

**Comment by barbalex** [comment]
> Da ich noch die erloschenen Tpop rausfiltern muss für die Abgabe, wäre ich sehr froh, wenn diese Spalte ebenfalls in den Exporten MassnahmenWebGisBun und KontrolleWebGisBun wären!

Ist ergänzt.

**Comment by barbalex** [comment]
TPOPKILMA ist offensichtlich ein Schreibfehler. Darum heisst die Spalte im Export TPOPKLIMA

**Comment by barbalex** [comment]
SAPTARTJAHR ist offensichtlich ein Schreibfehler. Darum heisst die Spalte im Export APSTARTJAHR

**Comment by barbalex** [comment]
Was ist Spalte "Tpop Staus"?

**Comment by barbalex** [comment]
Spalte "Tpop KontrID" existiert nicht mehr: Beim Frühlingsputz wurden die ID-Spalten in UUID umgewandelt. Daher wurde die bisherige GUID zur neuen id.

**Comment by barbalex** [comment]
> Massnahmen-Export (aus ArcGis-Tauglich fürs digitalisieren notwendig): AP Status, Umsetzung, Tpop Gemeinde, Tpop Flurname, Tpop Status, Massn GUID Alt

Hm. Jetzt wird eine ganze Menge dazu gefügt. Damit entspricht der Export nicht mehr den Anforderungen von WebGIS BUN, wie von der FNS erwartet. Das könnte ev. schon beim Status in Massnahmen und Kontrollen so sein.

Wieso soll das passieren?

Was bedeutet:

> aus ArcGis-Tauglich fürs digitalisieren notwendig

@csalzman: Was meinst du?

**Comment by wunderli** [comment]
Charlotte meint, dass könnte alles auch im WebGisBun-Export drin sein, wir bräuchten diese Spalten ja nicht in die Vorlage-Datenbank zu importieren.

Ansonsten reicht Tpopstatus fürs Filtern für WebGisBun.

Fürs Digitalisieren musste ich jeweils auch einen Massnahmen-Export haben, bisher habe ich einfach immer die Spaltenüberschriften angepasst.
Wenn es einfacher ist, evtl. ein separater Export dafür? 
Oder die Spalten-Namen bei allen Exporten GIS-tauglich?

Sonst muss ich halt weiterhin die Spalten aus dem kompletten Export anpassen.

Liebe Grüsse

Anna

**Comment by barbalex** [comment]
Vielleicht tut es auch der normale Massnahmen-Export? 

Seit dem Strukturumbau hat er gis-taugliche Feldnamen. Und enthält die erwähnten Felder.

**Comment by wunderli** [comment]
Hoi Alex

Dann ist ja alles bestens!
Habe den normalen Massnahmen-Export nicht mehr angeschaut.

Liebe Grüsse

Anna

-----------------------------------
Anna Wunderli
MSc Umw. Natw. ETH
topos Marti & Müller AG
Ökologische Beratungen
Idastrasse 24, 8003 Zürich

044 451 52 55
wunderli@toposmm.ch

**Comment by barbalex** [comment]
:-)
