### ISSUE TITLE
Absturz/Update

### ISSUE THREAD

**Issue by wunderli** [FNSKtZH/apflora#188]
Lieber Alex

Als ich heute die AP Flora öffnen wollte, gab es in beiden Browsern die Meldung "Update installieren".
Leider hat das nicht funktioniert und endete in einem Absturz.
Jetzt lässt sich die AP FloraDB gar nicht mehr öffnen.

Liebe Grüsse

Anna
![bildschirmfoto 2018-06-13 um 09 02 57](https://user-images.githubusercontent.com/26789445/41335616-a63dfa2a-6ee9-11e8-8375-6eb3282e10b0.png)
![bildschirmfoto 2018-06-13 um 09 02 47](https://user-images.githubusercontent.com/26789445/41335645-c31e8b82-6ee9-11e8-9170-66267815d416.png)

**Comment by wunderli** [comment]
![bildschirmfoto 2018-06-13 um 09 02 38](https://user-images.githubusercontent.com/26789445/41335679-edde0cd0-6ee9-11e8-9569-97b8d9c88267.png)

**Comment by barbalex** [comment]
Hoi Anna

Der bisher benutzte Daten-Server hat mich leider wieder verarscht. Ich
arbeite daran, apflora wieder verfügbar zu machen.

Bitte entschuldige.

LG, Alex



***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079 372 51 64
alex@barbalex.ch
www.barbalex.ch



Am Mi., 13. Juni 2018 um 09:12 Uhr schrieb wunderli <
notifications@github.com>:

**Comment by barbalex** [comment]
uups, geht schon lange wieder
übrigens: öffne neue issues bitte im neuen repository: https://github.com/barbalex/apf2/issues
