### ISSUE TITLE
OL-Karte mit TPop und allen Beob an Tpop

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#35]
Befehl auf Ebene TPop
öffnet Luftbild mit
- Ausschnitt passend
- alle Tpop beschriftet Pop/TPopNr
- alle zugeordneten Beob, beschriftet Pop/TPopnr
- alle nicht zugeordneten Beob, nicht beschriftet
- man kann zuordnen
- TPop nicht geclustert

**Comment by barbalex** [comment]
umgesetzt
