### ISSUE TITLE
Rechter Mausklick verdoppelt willkürlich TPops

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#44]
Es passiert immer wieder, aber nicht systematisch, dass wenn man rechte Maustaste im Stammbaum links drückt eine TPop unverzüglich verdoppelt wird.

**Comment by barbalex** [comment]
nach Telefon mit Topos vom 15.12.2016 folgende Bemerkungen:

- es _kann_ passieren, wenn man ein Menu öffnet, wenn man sich am unteren Rand des Strukturbaums befindet und das Menu nach oben öffnet: Es öffnet sich nämlich immer relativ zur linken unteren Ecke des geklickten Strukturelements, z.B. Teilpopulation
- vorausgesetzt wird aber, dass nach dem Rechtsklick noch ein Linksklick erfolgt. Was ich nach wie vor nicht provozieren kann (ausser extra zu klicken)
- in der künftigen Version von apflora wird sich das Menu relativ zur Mausposition öffnen. Somit ist die Maus immer am oberen linken des Menus (wenn man das Menu weit genug oberhalb des unteren Rand des Strukturbaums öffnet) bzw. unteren linken Rand des Menus (wenn man das Menu am unteren Rand des Strukturbaums öffnet). Da sich die Maus nun nicht über dem Menu befindet (ausser man würde sie noch bewegen), sollte der Fehler nicht mehr auftreten
- es gibt einen möglichen (unschönen) Flick für das Problem: Unten im Menu immer eine leere Zeile einfügen

**Comment by barbalex** [comment]
Habe jetzt gesehen, dass ein Menupunkt auch gewählt wird, wenn man ihn mit der _rechten_ Maustaste klickt. Zwar gibt es eine Einstellung im verwendeten Tool, um das zu verhindern - aber sie funktioniert nicht :-(

**Comment by barbalex** [comment]
Habe jetzt im verwendeten Tool eine Einstellung gefunden, mit der man das Menu relativ zum Mauszeiger öffnen kann - gleich wie in der künftigen Version von apflora. Habe es so gesetzt. Schliesse damit den issue - öffnet es wieder, falls damit das Problem nicht gelöst sein sollte.
