### ISSUE TITLE
TPop in andere Art kopieren oder verschieben

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#63]
Wunsch. Habe den Fall, dass es sich um eine falsche Bestimmung handelt. Kann nun aber Eingaben zur TPop nicht in die andere Art verschieben.

**Comment by barbalex** [comment]
hm. Kopieren kann man doch schon. Verschieben: warten, bis Fehler behoben, dann testen

**Comment by barbalex** [comment]
gemäss meinen Tests funktioniert es

**Comment by barbalex** [comment]
Korrektur: Kopieren funktioniert über Arten hinweg. Verschieben nicht

**Comment by barbalex** [comment]
Duplikat von https://github.com/FNSKtZH/apflora/issues/183
