### ISSUE TITLE
Jahresbericht 2014, Grundmengen

### ISSUE THREAD

**Issue by kmarti** [FNSKtZH/apflora#67]
Im Jahresbericht 2014 habe ich folgende Fehler festgestellt:
Allium angulosum; A. Grundmengen: Die Anzahl bekannte Pop/Teilpop stimmt nicht mit der Summe der Pop/TP mit verschiedenen Stati überein.
Dasselbe gilt für Aristolochia clematitis, Blackstonia acuminata und Carex chordorrhiza, Campanula cervicaria. Bei Aristolochia clematitis ist dies auch bei der Bestandeskontrolle "seit 2002" der Fall.
Bei Aldrovanda vesiculosa und Anagallis minima stimmen aber alle Zahlen.

Z.T. gibt es Fehler in den Daten, z.B. dass bei einzelnen TP der Status nicht ausgefüllt ist.
Einen systematischen Fehler habe ich bis jetzt entdeckt: Bei Arten ohne fertigen AP wie Aristolochia clematitis fehlt die Jahreszahl in Start Programm. Dann erscheinen die angesiedelten vor und nach Beginn AP nicht in der Grundmenge A. Ich werde dort überall als Start das Jahr 2030 angeben. Dies kann dann bei tatsächlichem Start angepasst werden.

**Comment by barbalex** [comment]
Hoi Karin

"Einen systematischen Fehler habe ich bis jetzt entdeckt: Bei Arten ohne
fertigen AP wie Aristolochia clematitis fehlt die Jahreszahl in Start
Programm. Dann erscheinen die angesiedelten vor und nach Beginn AP nicht in
der Grundmenge A. Ich werde dort überall als Start das Jahr 2030 angeben.
Dies kann dann bei tatsächlichem Start angepasst werden."

Das musst du vermutlich nicht machen.

Ich nehme an, die entsprechenden Pop/TPop sollen bei "Davon angesiedelt
(vor Beginn AP)" erscheinen. Richtig?

Ich habe soeben die entsprechenden Abfragen angepasst. Muss es selber noch
testen.

Gruss, Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 14:44 schrieb kmarti <notifications@github.com>:

**Comment by barbalex** [comment]
hm. Ich habe in ein paar Feldern für Teilpopulationen gefunden, dass mit
dem bekannt-seit-Feld der Population verglichen wurde, statt mit dem der
Teilpopulation

habe das korrigiert und prüfe das Ergebnis

Gruss, Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 14:44 schrieb kmarti <notifications@github.com>:

**Comment by barbalex** [comment]
Hoi Karin

Bei Aristolochia stimmt es jetzt beinahe.

Was jetzt noch falsch ist: 4 Pop haben den Status "angesiedelt nach Beginn
AP, aktuell". Es gibt aber kein ApJahr, daher listet die entsprechende
Abfrage diese Pop bei "Davon angesiedelt (nach Beginn AP)" nicht auf.
Dito bei 8 TPop.

Habt ihr falsch erfasst oder ist die Logik der Anwendung falsch?

Gruss, Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 14:44 schrieb kmarti <notifications@github.com>:

**Comment by kmarti** [comment]
Lieber Alex

Ich habe in der DB bei Aristolochia den Programm-Start 2030 eingefügt, jetzt aber wieder herausgenommen!

Eigentlich müssten alle angesiedelten Aristolochia-Populationen und -TP als angesiedelt vor Beginn AP erscheinen.
Den Status „angesiedelt nach Beginn AP" darf es bei Aristolochia gar nicht geben.

Herzliche Grüsse

Karin

--------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
marti@toposmm.ch

Am 08.01.2015 um 16:23 schrieb Alexander Gabriel <notifications@github.com>:

**Comment by barbalex** [comment]
Hoi Karin

Heisst das: Ihr passt die Stati an?
Oder soll der Bericht, wenn der AP noch nicht begonnen hat, diesen Status
im Feld "vor beginn AP" ausweisen?

Gruss, Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079/ 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 16:37 schrieb kmarti <notifications@github.com>:

**Comment by barbalex** [comment]
Hoi Karin

Hier ein fast aktuelles pdf (dauert halt ca. 30 Minuten, bis es entstanden
ist).

Gruss, Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079/ 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 16:37 schrieb kmarti <notifications@github.com>:

**Comment by kmarti** [comment]
Hoi Alex

Der Bericht sollte automatisch den Status „vor Beginn AP“ angeben, denn dazu gibt es ja gar keine Eingabefeld mehr bei den Stati.

Herzliche Grüsse

Karin

--------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
marti@toposmm.ch

Am 08.01.2015 um 16:40 schrieb Alexander Gabriel <notifications@github.com>:

**Comment by kmarti** [comment]
es fehlt der Anhang….

--------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
marti@toposmm.ch

Am 08.01.2015 um 16:42 schrieb Alexander Gabriel <notifications@github.com>:

**Comment by barbalex** [comment]
war schon dran, aber hier nochmals

Gruss, Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079/ 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 16:51 schrieb kmarti <notifications@github.com>:

**Comment by barbalex** [comment]
gemacht

bin grad das pdf am produzieren, muss aber bald die Kinder holen, wird also
später

Gruss, Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079/ 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 16:50 schrieb kmarti <notifications@github.com>:

**Comment by kmarti** [comment]
Hallo Alex

Es tut mir leid, aber ich sehe auch jetzt keinen Anhang. 

Herzliche Grüsse

Karin


Am 08.01.2015 um 17:00 schrieb Alexander Gabriel <notifications@github.com>:

> war schon dran, aber hier nochmals 
> 
> Gruss, Alex 
> 
> 
> 
> 
> *********************************************************** 
> 
> 
> 
> Alexander Gabriel 
> Wiesenstrasse 22 
> 8800 Thalwil 
> 079/ 372 51 64 
> alex@barbalex.ch 
> www.barbalex.ch 
> 
> 
> Am 8. Januar 2015 um 16:51 schrieb kmarti <notifications@github.com>: 
> 
> > es fehlt der Anhang…. 
> > 
> > -------------------------------- 
> > Karin Marti 
> > Dr.sc.nat.ETH 
> > topos Marti & Müller AG 
> > Idastrasse 24 
> > 8003 Zürich 
> > marti@toposmm.ch 
> > 
> > Am 08.01.2015 um 16:42 schrieb Alexander Gabriel <notifications@github.com>: 
> > 
> > 
> > > Hoi Karin 
> > > 
> > > Hier ein fast aktuelles pdf (dauert halt ca. 30 Minuten, bis es 
> > entstanden 
> > > ist). 
> > > 
> > > Gruss, Alex 
> > > 
> > > 
> > > 
> > > 
> > > *********************************************************** 
> > > 
> > > 
> > > 
> > > Alexander Gabriel 
> > > Wiesenstrasse 22 
> > > 8800 Thalwil 
> > > 079/ 372 51 64 
> > > alex@barbalex.ch 
> > > www.barbalex.ch 
> > > 
> > > 
> > > Am 8. Januar 2015 um 16:37 schrieb kmarti <notifications@github.com>: 
> > > 
> > > > Lieber Alex 
> > > > 
> > > > Ich habe in der DB bei Aristolochia den Programm-Start 2030 eingefügt, 
> > > > jetzt aber wieder herausgenommen! 
> > > > 
> > > > Eigentlich müssten alle angesiedelten Aristolochia-Populationen und 
> > -TP 
> > > > als angesiedelt vor Beginn AP erscheinen. 
> > > > Den Status „angesiedelt nach Beginn AP" darf es bei Aristolochia gar 
> > nicht 
> > > > geben. 
> > > > 
> > > > Herzliche Grüsse 
> > > > 
> > > > Karin 
> > > > 
> > > > -------------------------------- 
> > > > Karin Marti 
> > > > Dr.sc.nat.ETH 
> > > > topos Marti & Müller AG 
> > > > Idastrasse 24 
> > > > 8003 Zürich 
> > > > marti@toposmm.ch 
> > > > 
> > > > Am 08.01.2015 um 16:23 schrieb Alexander Gabriel < 
> > notifications@github.com>: 
> > > > 
> > > > 
> > > > > Hoi Karin 
> > > > > 
> > > > > Bei Aristolochia stimmt es jetzt beinahe. 
> > > > > 
> > > > > Was jetzt noch falsch ist: 4 Pop haben den Status "angesiedelt nach 
> > > > Beginn 
> > > > > AP, aktuell". Es gibt aber kein ApJahr, daher listet die 
> > entsprechende 
> > > > > Abfrage diese Pop bei "Davon angesiedelt (nach Beginn AP)" nicht 
> > auf. 
> > > > > Dito bei 8 TPop. 
> > > > > 
> > > > > Habt ihr falsch erfasst oder ist die Logik der Anwendung falsch? 
> > > > > 
> > > > > Gruss, Alex 
> > > > > 
> > > > > 
> > > > > 
> > > > > 
> > > > > *********************************************************** 
> > > > > 
> > > > > 
> > > > > 
> > > > > Alexander Gabriel 
> > > > > Wiesenstrasse 22 
> > > > > 8800 Thalwil 
> > > > > 079 372 51 64 
> > > > > alex@barbalex.ch 
> > > > > www.barbalex.ch 
> > > > > 
> > > > > 
> > > > > Am 8. Januar 2015 um 14:44 schrieb kmarti <notifications@github.com>: 
> > 
> > > > > 
> > > > > > Im Jahresbericht 2014 habe ich folgende Fehler festgestellt: 
> > > > > > Allium angulosum; A. Grundmengen: Die Anzahl bekannte Pop/Teilpop 
> > > > stimmt 
> > > > > > nicht mit der Summe der Pop/TP mit verschiedenen Stati überein. 
> > > > > > Dasselbe gilt für Aristolochia clematitis, Blackstonia acuminata 
> > und 
> > > > Carex 
> > > > > > chordorrhiza, Campanula cervicaria. Bei Aristolochia clematitis 
> > ist 
> > > > dies 
> > > > > > auch bei der Bestandeskontrolle "seit 2002" der Fall. 
> > > > > > Bei Aldrovanda vesiculosa und Anagallis minima stimmen aber alle 
> > > > Zahlen. 
> > > > > > 
> > > > > > Z.T. gibt es Fehler in den Daten, z.B. dass bei einzelnen TP der 
> > > > Status 
> > > > > > nicht ausgefüllt ist. 
> > > > > > Einen systematischen Fehler habe ich bis jetzt entdeckt: Bei Arten 
> > > > ohne 
> > > > > > fertigen AP wie Aristolochia clematitis fehlt die Jahreszahl in 
> > Start 
> > > > > > Programm. Dann erscheinen die angesiedelten vor und nach Beginn AP 
> > > > nicht in 
> > > > > > der Grundmenge A. Ich werde dort überall als Start das Jahr 2030 
> > > > angeben. 
> > > > > > Dies kann dann bei tatsächlichem Start angepasst werden. 
> > > > > > 
> > > > > > — 
> > > > > > Reply to this email directly or view it on GitHub 
> > > > > > <https://github.com/FNSKtZH/apflora/issues/67>. 
> > > > > > 
> > > > > — 
> > > > > Reply to this email directly or view it on GitHub. 
> > > > > 
> > > > 
> > > > — 
> > > > Reply to this email directly or view it on GitHub 
> > > > <https://github.com/FNSKtZH/apflora/issues/67#issuecomment-69196208>. 
> > > > 
> > > — 
> > > Reply to this email directly or view it on GitHub. 
> > > 
> > 
> > — 
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/FNSKtZH/apflora/issues/67#issuecomment-69198641>. 
> >
> —
> Reply to this email directly or view it on GitHub.
> 

---------------------------------------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
marti@toposmm.ch

**Comment by barbalex** [comment]
oh, jetzt ist alles klar: Du hast keinen Anhang erhalten, weil diese Mail
über die issues auf GitHub läuft...
Ich hab das gar nicht bemerkt

Herzliche Grüsse
Alex




***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079/ 372 51 64
alex@barbalex.ch
www.barbalex.ch


Am 8. Januar 2015 um 22:26 schrieb kmarti <notifications@github.com>:

**Comment by barbalex** [comment]
ist soviel ich weiss erledigt
