### ISSUE TITLE
Export TPop inkl. letzte Kontrolle

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#69]
Hier fehlt die tatsächliche Kontrolle (Einheiten und Anzahl)

**Comment by barbalex** [comment]
das hätte zur Folge, dass, wenn mehrere Zählungen existieren, die Zeilen
(Kontrollen) vervielfältigt werden

wollt ihr das?

das war mir nicht klar, daher habe ich es (noch) nicht gemacht


Am 6. Februar 2015 um 08:22 schrieb csalzmann <notifications@github.com>:

**Comment by barbalex** [comment]
Zählung ergänzt
