### ISSUE TITLE
TPop Anz Kontr inkl. letzte Kontrolle

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#71]
Bitte TPopBer Entwicklung aufschlüsseln (Text statt Nummern), ebenso TPop fuer AP-Bericht relevant.

**Comment by barbalex** [comment]
TPopBer Entwicklung ist docodiert.
TPop fuer AP-Bericht relevant: das ist wie bei allen ja/nein bzw. true/false Feldern: 0 ist nein, 1 ist ja.
