### ISSUE TITLE
TPop Anz Kontr inkl. letzte Kontrolle, auch noch nie kontrollierte aufführen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#72]
Sollte eigentlich ALLE TPops enthalten, also auch diejenigen ohne Kontrolle. Ich meine, das war vorher auch so. Es ist DIE Abfrage, von der aus wir entscheiden, welche TPops jeweils kontrolliert werden sollten, deshalb ist es auch sehr wichtig, dass die noch nicht kontrollierten aufgelistet sind.

**Comment by barbalex** [comment]
das bedingt mehrere hintereinander geschaltete views (ca. 7!)
beim vor-vor-letzten braucht mein PC 1.5 Minuten, um ihn aufzubauen
msql auf den Server wurde davon völlig überfordert - musste soeben den Server neu starten

hm

**Comment by barbalex** [comment]
es funktioniert lokal, aber der Server ist offenbar überfordert

hm

**Comment by csalzmann** [comment]
oh oh.

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch




Am 13.02.2015 um 13:00 schrieb Alexander Gabriel <notifications@github.com>:

**Comment by barbalex** [comment]
tja, diese Abfrage muss ich jeweils auf meinem PC ausführen - der ist leistungsfähiger als der Server
ich muss dann jeweils die neusten Daten kopieren, d.h. ich brauch dazu ca. 15 Minuten

wir könnten auch den Server aufrüsten - bin aber nicht sicher, wie viel mehr Saft er braucht, daher weiss ich nicht, wie teuer das kommen würde
