### ISSUE TITLE
Populationen, AP-Bericht relevant

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#73]
Wie lassen sich nicht-relevante Pops aussortieren? Bei TPop kann man das ja eingeben, bei Pops nicht.

**Comment by barbalex** [comment]
Pop ist nicht relevant, wenn keine TPop relevant ist

auf dem Handy geschrieben
Am 19.02.2015 17:00 schrieb "csalzmann" <notifications@github.com>:
