### ISSUE TITLE
Berichte können nicht erstellt werden

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#74]
Im Moment können weder (T)Pop-Berichte noch (T)Pop-Massnahmenberichte erstellt werden
![bildschirmfoto 2015-03-10 um 17 26 20](https://cloud.githubusercontent.com/assets/6047564/6579533/14d86230-c74b-11e4-8dd4-c85deedbfe2e.png)

**Comment by barbalex** [comment]
ouch!

Das war ein Fehler in meinen brandneuen Triggers, auf die ich so stolz war...
Schade, dass wir keine Test haben - damit seid ihr die Versuchkaninchen.

Es ist korrigiert.

Alex
