### ISSUE TITLE
auf CH-Karten verorten funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#76]
Funktioniert nicht (es öffnet sich keine Karte)
Habe danach neue Koordinaten von Hand eingegeben, daraufhin waren eine zeitlang an verschiedenen Orten die gleiche TPop angezeigt, "Neu laden" hat im Fenster rechts nicht mehr funktioniert. Danach "Neu laden" im Stammbaum, jetzt hats die TPop kopiert (aber ohne Inhalt).
![bildschirmfoto 2015-04-20 um 16 25 44](https://cloud.githubusercontent.com/assets/6047564/7233595/37a89ef4-e782-11e4-9f7a-5f6cbb0b4f3b.png)

![bildschirmfoto 2015-04-20 um 16 26 44](https://cloud.githubusercontent.com/assets/6047564/7233601/3da6e252-e782-11e4-9e95-d154aa80e577.png)

**Comment by barbalex** [comment]
Hoi Charlotte

Leider kann ich das nicht nachvollziehen. Zumindest nicht auf Chrome auf Windows.
Kannst du es nochmals nachvollziehen? Und mir genau sagen:
* Browser
* Betriebssystem
* Programm, PopNr und TPopNr (ich konnte es auf Ophrys araneola Rchb. (Spinnen-Ragwurz) / 23 / 2 nicht nachvollziehen)
* was du vorher gemacht hast. Am besten ist, wenn du diesen Fehler direkt nach einem Neu-Laden der Anwendung provozieren kannst, z.B. ohne zuvor TPop kopiert zu haben. Oder genau beschreiben kannst, was man vorher machen muss, damit dieser Fehler auftritt

Herzliche Grüsse
Alex

**Comment by csalzmann** [comment]
Ich arbeite jetzt auf Mac mit Chrome Version 46.0.2490.86 (64-bit)

Auf Google Karten verorten geht tipptopp, auf CH-Karten kann man TPop mit der Maus gar nicht "fassen" und deshalb auch nicht bewegen.

**Comment by barbalex** [comment]
Was willst du fassen: Das Symbol mit der Blume? 

Ätsch, OpenLayers hat dich reingelegt: Du musst den blauen Punkt darunter fassen. Und damit das nicht so langweilig ist, taucht er erst auf, wenn du mit der Maus in die Nähe kommst.

Zugegeben, nicht wirklich die Beste Benutzerführung...

Oder hast du ein anderes Problem?

**Comment by csalzmann** [comment]
Grins, bin ich voll reingefallen!

Dann zeigen wir das nächste Woche aber grad auch noch!

Danke.

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
