### ISSUE TITLE
Pop/TPop auf Schweizer Karten anzeigen - selektiver Export funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#79]
![bildschirmfoto 2015-11-12 um 09 14 20](https://cloud.githubusercontent.com/assets/6047564/11113548/231f03a4-891e-11e5-893d-361b396935f4.png)

Ich denke, diese Funktion ist grundsätzlich auch nicht so wichtig, weil man die Info ja aus dem Gesamtexport herausfiltern kann. Bei GoogleEarth werden diese Funktionen auch gar nicht angeboten.

**Comment by barbalex** [comment]
das war ein Fehler in meinem Code
Ist korrigiert, wird beim nächsten Update heute Nacht aktiv
