### ISSUE TITLE
Ansicht TPop im GIS Browser 

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#80]
Man kommt immer an gleichen (falschen) Ort

**Comment by barbalex** [comment]
Bei mir funktioniert es immer, wenn ein Punkt erfasst wurde. Mindestens die zwei Beispiele, die ich ausprobiet habe. Kannst du ein Beispiel nennen?

**Comment by csalzmann** [comment]
Lieber Alex

Habe grad gemerkt - immer an den gleichen Ort spickt der GIS Browser doch nicht, jetzt spickt er immer an einen anderen Ort..

Also hier mein Bsp:










---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

**Comment by barbalex** [comment]
uh, hast du ein Beispiel eingefügt? Scheint nicht geklappt zu haben. Schick mir allfällige Bilder ev. besser direkt per mail

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
