### ISSUE TITLE
Innerhalb Menü TPop Beobachtungen zuordnen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#81]
Innerhalb des Menüs TPop kann man auch "auf CH-Karten Beobachtungen zuordnen". Diese Funktion funktioniert hier aber nicht. Im Menüpunkt Beobachtungen kann man es aber. Evtl. bei TPops löschen?

**Comment by barbalex** [comment]
Funktioniert wieder, ist repariert.
Das gab es vorher bei Beobachtungen nicht. Habe ich ergänzt.
