### ISSUE TITLE
Distanz messen - Blume

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#83]
Wenn man Distanz misst (TPop, auf CH-Karten zeigen), dann wird am Ende eine Blumensymbol violett mit blauem Punkt erstellt, das man nicht mehr los wird, z.T. muss man sogar neu laden.

**Comment by barbalex** [comment]
bestätigt. Das passiert offenbar jetzt immer, wenn Geometrien bearbeitbar gemacht werden

**Comment by barbalex** [comment]
hm. Nein, ich kann es doch nicht nachvollziehen: Bei mir verschwindet der blaue Punkt, sobald ich die Funktion zum Messen ausschalte

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
