### ISSUE TITLE
Aus Beobachtung neue Pop, Eingabehilfen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#88]
Folgende Felder werden von der Beobachtung direkt übernommen:

in TPop

bekannt seit:  A_NOTE
Gemeinde: NOM_COMMUNE
Flurname: DESC_LOCALITE_

In Pop
bekannt seit:  A_NOTE

**Comment by barbalex** [comment]
siehe auch: https://github.com/FNSKtZH/apflora/issues/88

**Comment by barbalex** [comment]
umgesetzt
