### ISSUE TITLE
Beobachtungen zuordnen - Eingabehilfe Koordinaten in TPop

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#90]
Es wäre auch nützlich, wenn man die Koordinaten einer zugeordneten  Beobachtung in Tpop kopieren könnte (das wäre ein Fall, wo man die Beobachtung einer bereits existierenden TPop zugeordnet hat - die Koordinaten der Beobachtung aber als präziser einschätzt als diejenigen der bereits existierenden TPop).

**Comment by barbalex** [comment]
ist umgesetzt
