### ISSUE TITLE
Beobachtungen zuordnen - nach Zuordnung im Baum zur TPop springen

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#93]
Nach der Zuordnung muss man ja immer die Angaben in der TPop kontrollieren und allenfalls anpassen

**Comment by barbalex** [comment]
Ist das sicher immer, was die Benutzerin will?

Denn wenn das jemand nicht will, kann es ganz schön ärgerlich sein.

Z.B. kann man nicht mehr nacheinander mehrere Arten zuordnen, weil die Karte ja nach der Zuordnung schliesst und man die TPop vor sich hat. Also zurück zur Karte, wieder reinzoomen...

Auch kann man nicht mehr Bemerkungen zur Zuordnung erfassen. Aber vielleicht macht man das ja kaum je?

Ich kann mir eher vorstellen, dass, wenn man in der Karte zuordnet, nicht nur das Fenster für die Beobachtung öffnet, sondern auch eines für die TPop. Ev. sind halt beide im selben Fenster, in unterschiedlichen Reitern.

**Comment by csalzmann** [comment]
Nutzen darin: meist muss man Jahreszahl "bekannt seit" anpassen. Können wir aber noch besprechen.

**Comment by barbalex** [comment]
ist umgesetzt
