### ISSUE TITLE
Massnahmen kopieren und einfügen funktioniert nicht mehr

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#95]
![bildschirmfoto 2015-11-25 um 14 32 38](https://cloud.githubusercontent.com/assets/6047564/11398484/659881b6-9381-11e5-8666-1409116421d7.png)

**Comment by barbalex** [comment]
Kannst du beschreiben, aus welcher TPop du welche Massnahme ausschneidest und in welche du sie einfügen willst?

Ich frage genau nach, weil es in meinem Test funktioniert.

**Comment by barbalex** [comment]
o.k., ich hab's: der Fehler tritt auf, wenn man die Massnahme ausschneidet und in eine TPop einer anderen Pop einfügen will

**Comment by barbalex** [comment]
das war ein dummer Fehler in der Programmierung
ist (hoffentlich) behoben
