### ISSUE TITLE
Beobachtungen: Bemerkungen zu "Nicht zuzuordnenden"

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#96]
Habe Mühe, Bemerkungen bei "nicht zuzuordnenden" anzubringen, es braucht meist mehrere Anläufe (Bemerkungen werden nicht gespeichert). Siehe auch Fehlermeldung.
![bemerkungen](https://cloud.githubusercontent.com/assets/6047564/11437328/3ee565c6-94ed-11e5-8469-835f39bd749b.JPG)

**Comment by barbalex** [comment]
ist repariert
Himmel, ist das Spaghetti-Code.
Ein Wechsel zu React und Flux ist dringend nötig. Das werde ich als Teil des neuen Strukturbaums machen.
