### ISSUE TITLE
Beobachtungen: nicht zuzuordnende verdoppelt

### ISSUE THREAD

**Issue by csalzmann** [FNSKtZH/apflora#99]
Bei den nicht zuzuordnenden stimmt nicht nur etwas nicht mit den Bemerkungen, ich habe jetzt auch gemerkt, dass sich einige von diesen Beobachtungen verdoppelt haben (Oder waren sie von Anfang an mehrmals drin? Wäre wiederum auch komisch). Ausserdem gibt es da Kombinationen, die unmöglich sind (Auswahl bei einer TPop, gleichzeitig bei den nicht zuzuordnenden). Siehe Screenshot.
![beobachtunen_doppelt](https://cloud.githubusercontent.com/assets/6047564/11439486/001e465a-94fc-11e5-8124-2e7c8a9ea020.JPG)

**Comment by barbalex** [comment]
wegen neuer Anwendung obsolet
